export const SET_ISBISIESTO = 'SET_ISBISIESTO';
export const CLEAR_ISBISIESTO = 'CLEAR_ISBISIESTO';

export const ACCOUNT_FETCHING = 'ACCOUNT_FETCHING';
export const ACCOUNT_FETCH_SUCCESS = 'ACCOUNT_FETCH_SUCCESS';
export const ACCOUNT_FETCH_FAILED = 'ACCOUNT_FETCH_FAILED';

export const ACCOUNT_CREATING = 'ACCOUNT_CREATING';
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS';
export const ACCOUNT_CREATE_FAILED = 'ACCOUNT_CREATE_FAILED';
